// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.UIKit;

namespace PagingDemo
{
	public partial class ViewControllerWithImage : UIViewController
	{
		public ViewControllerWithImage (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            UpdateImageView();
        }

        UIImage _image;
        public UIImage Image
        {
            get {return _image;}
            set
            {
                _image = value;
                UpdateImageView();
            }
        }

        void UpdateImageView()
        {
            if (imageView != null)
                imageView.Image = Image;
        }

        protected override void Dispose(bool disposing)
        {
            if(Image != null)
            {
                Image.Dispose();
                Image = null;
            }

            base.Dispose(disposing);
        }
	}
}
